apiVersion: v1
kind: Pod
metadata:
  name: secure-demo
spec:
  securityContext:
    runAsNonRoot: true
    fsGroup: 2000
  containers:
  - name: demo
    image: ghcr.io/bajajmohit/demo-api:latest
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsUser: 1001
    ports:
    - containerPort: 8080
